services:
  web:
    image: my-nextjs-app2:latest
    container_name: nextjs_container
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
    restart: unless-stopped
